CREATE DATABASE `sp4v1` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE DATABASE `sp4v1Test` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE USER 'sp4admin'@'localhost' IDENTIFIED BY 'SP4!Min*';GRANT USAGE ON *.* TO 'sp4admin'@'localhost' IDENTIFIED BY 'SP4!Min*' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `sp4v1`.* TO 'sp4admin'@'localhost';

CREATE USER 'sp4adminTest'@'localhost' IDENTIFIED BY 'SP4!Min*';GRANT USAGE ON *.* TO 'sp4adminTest'@'localhost' IDENTIFIED BY 'SP4!Min*' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `sp4v1Test`.* TO 'sp4adminTest'@'localhost';
